### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by Rhedox** [afollestad/material-cab#12]
It crashes on initialization due to changes in Support Library 23.2

The actual exception:
`java.lang.NoSuchFieldError: No static field abc_ic_ab_back_mtrl_am_alpha of type I in class Lcom/afollestad/materialcab/R$drawable; or its superclasses (declaration of 'com.afollestad.materialcab.R$drawable' appears in /data/app/rhedox.gesahuvertretungsplan-2/base.apk)
                                                                                at com.afollestad.materialcab.MaterialCab.reset(MaterialCab.java:86)
                                                                                at com.afollestad.materialcab.MaterialCab.<init>(MaterialCab.java:65)`

It seems like the back button drawable "abc_ic_ab_back_mtrl_am_alpha" got removed or replaced by a similar VectorDrawable.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-cab/releases/tag/0.1.9

**Comment by Rhedox** [comment]
Can you also update the gradle package?
